import { ApolloWrapper } from "@/libs/apollo-provider";
import "./globals.css";
import { Inter } from "next/font/google";
import { loadErrorMessages, loadDevMessages } from "@apollo/client/dev";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

if (process.env.NODE_ENV) {
  // Adds messages only in a dev environment
  loadDevMessages();
  loadErrorMessages();
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-gray-200">
      <body className={inter.className}>
        {" "}
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
